"""change names again in database

Revision ID: 18be9f43bff5
Revises: 0da3923e7ff9
Create Date: 2024-10-14 00:44:44.357761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '18be9f43bff5'
down_revision: Union[str, None] = '0da3923e7ff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('recipe_id', sa.Integer(), nullable=True))
    op.add_column('ingredients', sa.Column('categoryIngredient_id', sa.Integer(), nullable=True))
    op.drop_constraint('ingredients_ibfk_1', 'ingredients', type_='foreignkey')
    op.drop_constraint('ingredients_ibfk_2', 'ingredients', type_='foreignkey')
    op.create_foreign_key(None, 'ingredients', 'categoryIngredients', ['categoryIngredient_id'], ['idCategoryIngredient'])
    op.create_foreign_key(None, 'ingredients', 'recipes', ['recipe_id'], ['idRecipe'])
    op.drop_column('ingredients', 'categoryIdIngredient')
    op.drop_column('ingredients', 'recipeId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('recipeId', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ingredients', sa.Column('categoryIdIngredient', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ingredients', type_='foreignkey')
    op.drop_constraint(None, 'ingredients', type_='foreignkey')
    op.create_foreign_key('ingredients_ibfk_2', 'ingredients', 'recipes', ['recipeId'], ['idRecipe'])
    op.create_foreign_key('ingredients_ibfk_1', 'ingredients', 'categoryIngredients', ['categoryIdIngredient'], ['idCategoryIngredient'])
    op.drop_column('ingredients', 'categoryIngredient_id')
    op.drop_column('ingredients', 'recipe_id')
    # ### end Alembic commands ###
