# pylint: skip-file
"""fourth migration

Revision ID: 2282fe19bf2e
Revises: ecc05486e874
Create Date: 2024-10-13 01:36:58.917298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2282fe19bf2e'
down_revision: Union[str, None] = 'ecc05486e874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('familyId_id', sa.Integer(), nullable=True))
    op.drop_constraint('users_ibfk_2', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'families', ['familyId_id'], ['idFamily'])
    op.drop_column('users', 'familyId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('familyId', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_ibfk_2', 'users', 'families', ['familyId'], ['idFamily'])
    op.drop_column('users', 'familyId_id')
    # ### end Alembic commands ###
