"""change names in database again

Revision ID: 533eb3c58de9
Revises: 18be9f43bff5
Create Date: 2024-10-21 15:16:49.835869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '533eb3c58de9'
down_revision: Union[str, None] = '18be9f43bff5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pantries', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('pantries_ibfk_1', 'pantries', type_='foreignkey')
    op.create_foreign_key(None, 'pantries', 'users', ['user_id'], ['idUser'])
    op.drop_column('pantries', 'userId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pantries', sa.Column('userId', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pantries', type_='foreignkey')
    op.create_foreign_key('pantries_ibfk_1', 'pantries', 'users', ['userId'], ['idUser'])
    op.drop_column('pantries', 'user_id')
    # ### end Alembic commands ###
